### ISSUE TITLE
CN crash when left shifting unsigned char or short

### ISSUE THREAD

**Issue by peterohanley** [rems-project/cerberus#233]
`x.c`:
```
void a(void)
{
    unsigned char b = 0;
    b << 0;
}
```
```
% cn x.c 
[1/1]: a
cn: internal error, uncaught exception:
    File "backend/cn/check.ml", line 649, characters 5-11: Assertion failed
    Raised at Dune__exe__Check.check_pexpr in file "backend/cn/check.ml", line 649, characters 5-98
    Called from Dune__exe__Typing.pure in file "backend/cn/typing.ml", line 102, characters 22-25
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.pure in file "backend/cn/typing.ml", line 102, characters 22-25
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.pure in file "backend/cn/typing.ml", line 102, characters 22-25
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.pure in file "backend/cn/typing.ml", line 102, characters 22-25
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.run in file "backend/cn/typing.ml", line 44, characters 16-19
    Called from Dune__exe__Main.main in file "backend/cn/main.ml", line 182, characters 20-87
    Called from Dune__exe__Main.main in file "backend/cn/main.ml", line 178, characters 9-1023
    Re-raised at Dune__exe__Main.main in file "backend/cn/main.ml", line 222, characters 8-73
    Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
    Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
```

The assert is here: https://github.com/rems-project/cerberus/blob/14508c54d7b139108ca0b967124c50054e97ff11/backend/cn/check.ml#L649

`char` is ok, `short` is ok, unsigned version of either is not ok. unsigned and signed ints are ok.

**Comment by septract** [comment]
Partially addressed this in #461 - I converted the uncontrolled crash into a controlled error, but didn't add support for the missing types

**Comment by septract** [comment]
Based on the discussion with @cp526 in #461, this is actually a bug in CN, not a missing feature as I had assumed. Someone who understands CN more deeply should take a look at what's going on.

**Comment by yav** [comment]
OK, so I think I figured out the issue here.   What's happening is that because of the promotion rules, `unsigned char` gets promoted to `signed int`, according to this rule in the standard:

> If an int can represent all values of the original type, the value is converted to an int;
> otherwise, it is converted to an unsigned int.

(see `ailTypeAux.lem` for the implementation of this rule)

Section 6.5.7 of the C standard, which defines the shift operators says:

> The integer promotions are performed on each of the operands. The type of the result is
> that of the promoted left operand.

However, if you look at [line 1619](https://github.com/rems-project/cerberus/blob/32ee9414b9766e3efb4c2a9a57455191b73c880e/frontend/model/translation.lem#L1619) of `translation.lem` you can see the logic about signedness is made based on the *unpromoted* type of the first operand, which leads to the confusion.   Assuming that things are already type-checked,
a simple fix would be to just change `(ctype_of e1)` to `result_ty`.   I tried that and it seems to fix the problem.

@kmemarian if you think my analysis is correct I'd be happy to make a PR (or you can just do it since it's a tiny tweak).  Let me know.

**Comment by kmemarian** [comment]
@yavor This is something where the text of the standard confuses me, it says (§6.5.7#4):

"If **`E1`** has an unsigned type, the value of the result is **`E1 × 2^E2,`** reduced modulo
one more than the maximum value representable in the result type."

and

"If **`E1`** has a signed type and nonnegative value, and **`E1 × 2^E2`** is representable in the result type, then that is the resulting value; otherwise, the behavior is undefined.".

The fact that it talks about the type of **`E1`** directly (and later in the same sentence refers to the result type, i.e. the promoted type) made me interpret this as meaning the type *before promotion* (I even updated the CI tests [0108-shifts.c](https://github.com/rems-project/cerberus/blob/master/tests/ci/0108-shifts.c) to document this, but should have also added something in `translation.lem`...).

Do you think that it is instead meant be read as *E1 after promotion*?

**Comment by yav** [comment]
I was looking at the previous paragraph, 6.5.7#3.  It starts like this:

> The integer promotions are performed on each of the operands. The type of the result is that of the promoted left operand. 

The way I understand is that you first do promotion on the arguments, and then you compute the results according to paragraph 4 & 5 for left and right shift respectively.

**Comment by cp526** [comment]
This seems to now be resolved, following @yav 's (+ @kmemarian 's ?) changes.
