### ISSUE TITLE
[CN] Re-introduce disjoint and non-null constraints from resources

### ISSUE THREAD

**Issue by dc-mak** [rems-project/cerberus#295]
At some point (@cp526 can you please find which commit deleted the feature?) automatic constraints on the disjointness and non-null-ness of stack variable addresses were removed for performance reasons. This leads to code like the below to exclude such cases
https://github.com/rems-project/cerberus/blob/f61caee13f0d09811db927f04b881941b1a18f6b/tests/cn_vip_testsuite/pointer_offset_from_ptr_subtraction_auto_xy.error.c#L12-L14

Likely a few days work to re-introduce, perhaps underneath a switch if performance is substantially worse in this case.

**Comment by septract** [comment]
Here's an example of something we'd like to prove, but that currently doesn't seem to be possible: 
```
void ownership_1(int *a, int *b)
/*@ 
requires 
  take P1 = Owned(a); 
  take P2 = Owned(b);
ensures 
  a != b; 
@*/
{
  /*@ split_case a == b; @*/
  ; 
}
```

This example should be provable, because the precondition should enforce that `a != b`. 

I'm also not sure whether the logic is sound if you don't enforce disjointness. How does the frame property even hold in that case?

**Comment by cp526** [comment]
Agreed, we definitely want CN to be able to prove the `a != b`. 

There's no soundness issue though. CN's resource typing has the disjointness of `a` and `b` "built-in": e.g. a store that requires ownership of just `a` will consume the `Owned(a)` and produce an updated one, leaving `Owned(b)` unchanged.

The reason for CN's current inability to prove `a != b` is due to the fact that constraints implied by resource ownership (such as  `a != b`) are not made available to the smt solver (which is where the postcondition `a != b` should be proved).
