### ISSUE TITLE
[CN] simplify guards in `each` terms in state output

### ISSUE THREAD

**Issue by peterohanley** [rems-project/cerberus#351]
I got a program with this term in the Available resources: `each(u64 j; (((j < 4u64) && (!(j == 0u64))) && (!(true && (j < 2u64)))) && (!(j == 2u64))) {Block<struct instrumentation_state>(&instrumentation + j * 44u64 /* 0x2c */)}(ii) (same type)`

I simplified `(((j < 4u64) && (!(j == 0u64))) && (!(true && (j < 2u64)))) && (!(j == 2u64))` to `((j < 4u64) && (j >= 3u64))` manually. This is much easier to read. I might have made a mistake.

Simplifying terms in general might be tricky but at least
`(!(true && (j < 2u64)))` should be amenable to local simplification to `(j >= 2u64)`.

**Comment by cp526** [comment]
Agreed. 

This particular simplification would be easy to add. We might want to see if we can replace CN's (somewhat adhoc) term simplifier with simplification using the SMT solver, which would be much better at it.

**Comment by bcpierce00** [comment]
This sounds like a useful step!

**Comment by yav** [comment]
I believe the constraint in this case should just simplify to `j = 3`.
Both CVC5 and Z3 have a `simplify` command (it's not standard SMTLIB I think, but since it works in both, it's probably OK to use).  I tried it on this example, and this is what both of them come up with:
```
(! (j >= 4)) && (! (j == 0)) && (j >= 2) &&  (! (j == 2))
```
This is really not much different from the original, it pretty much jsut removed the `true &&`.

Also translating to the solver makes some things into uninterpreted functions, which probably are less amenable to simplification than if we know the meaning of the terms.  So I suspect we'd need some manual simplificaiton anyways, but it'd be interesting if we can also use the solver to help.
