### ISSUE TITLE
[CN] the solver is using a lot of pipes

### ISSUE THREAD

**Issue by kmemarian** [rems-project/cerberus#369]
When running the CN ci tests (`tests/run-cn.sh`) on macOS (tested on 14.5) 10 tests fail because the `cn` process runs out of file descriptors (the macOS's default soft limit appears to be 256):

```
10 tests failed:
   ./cn/tree16/as_partial_map/tree16.c ./cn/tree16/as_mutual_dt/tree16.c ./cn/fun_ptr_three_opts.c ./cn/list_rev01.c ./cn/append.c ./cn/reverse.c ./cn/mutual_rec/mutual_rec.c ./cn/fun_ptr_known.c ./cn/mergesort.c ./cn/fun_ptr_extern.c
```

I think that the issue is a result of:
1. every call to `Simple_smt.new_solver` opens 3 pipes as a result of the call to `Unix.open_process_args_full`.
2. every call to `Solver.model_evaluator _ _` (called from `Solver.provable`) creates a new solver, whose lifetime extends until the end of the execution of CN (?).

**Comment by septract** [comment]
cc @yav

**Comment by yav** [comment]
I don't see a way around (1), but we could change (2) to start a solver only when it needs to evaluate in the context of a model, and end the solver when it is done.   It will likely make model evaluation a bit slower because we'll pay the start up cost multiple times, but I am not sure if that matters.

Another option for (2) would be to change the API to bracket calls to the model evaluator (e..g, something like `with_model_evaluator f` where `f` will be given a solver setup with the particular model.

Thoughts?

**Comment by yav** [comment]
Here's an idea on how we can improve the situation here:
  1. Only ever use a single solver for evaluating models
  2. This solver is only started the first time we need to evaluate a model
  3. Come up with a "name" for the models (could be just an integer from some counter), so that we can keep track on what models is currently loaded up in the model evaluator solver,.
  4. When we are asked to evalute something in the context of the model we need to:
     - Check if we have a model solver, if not start it and load up the current model
     - If we have a solver, check that the model in it matches the currently loaded one; if not, load the correct model
     - Do the evaluation as now.
     
This would reduce the number of solver from `1 + N`, where `N` is the number of model to just 2, which should be better.  I also think that usually we use the models many times in a row, and then we are done with them, so remember which model is loaded up is likely to reduce overhead due to switching model constantly.

As a bonus, we could also add a timeout thread that will occasionally stop the model evaluator if it has not been used for a while, but I am not sure if this is really necessary.

One thing we'd have to be careful about is how to log the interactions with the solver doing the model evaluation, although these are generally a lot less useful than the interactions with the solver that does the solving.  The logging is still useful for debugging though, so we should not completely disable it.

**Comment by peterohanley** [comment]
@dsainati1 You mentioned you couldn't reproduce it. A different reproduction stopped working on the most recent version but this one works on latest. Interestingly there aren't even any CN annotations left.
```
% cn --version
git-77cdad7dc [2024-08-28 08:53:13 -0700]
```

```
typedef long long int64_t;

typedef unsigned char uint8_t;

typedef unsigned short uint16_t;

typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;
typedef char __darwin_uuid_string_t;
struct __darwin_pthread_handler_rec {
  char __opaque[8];
};
struct _opaque_pthread_once_t {
  long __sig;
  char __opaque[8][192];
};
struct _opaque_pthread_rwlockattr_t {
  struct __darwin_pthread_handler_rec *__cleanup_stack;
};
typedef unsigned long uintptr_t;

static uint8_t f_22() {
  return 4;
  3;
  0;
  1;
  2;
  3;
  0;
}

static uint8_t f_32() {
  uint8_t d_33[3];
  uint8_t d_34[3];
}

int f_37();

struct s_39 {
  uint8_t d_40[2];
  uint8_t d_41[2];
};
int f_43(struct s_39 *a);

uint32_t sensors[2][2];
uint8_t d_46[4];
extern uint8_t d_47[2][2];
extern uint8_t d_48[2][2];
extern uint8_t d_49[2][2][2];
int d_50;

typedef int size_t;
uint16_t _OSSwapInt16(_data) {}
uint32_t _OSSwapInt32(_data) { _data = __builtin_bswap32(_data); }
struct {
  uint64_t __val;
} __attribute__();
uint16_t OSReadSwapInt16(_offset) {}
uint32_t OSReadSwapInt32() {}
uint64_t OSReadSwapInt64() {}
void f_61(_data){}
int f_62(FILE);

int fflush0;
typedef struct {
  int64_t tv_sec;
};
typedef int clockid_t;
int f_69(clockid_t, struct timespec *);

int f_71(void);

void f_73() {
  for (int i = 0; i < 4;)
    for (int c = 0; c < 2; ++c) {
      for (int s = 0; s < 2; ++s) {
        switch (d_47[c][s]) {
        case 0:
        case 1:
          d_49[c][s][0] = 1;
        case 3:
          d_48[c][s] = 1;
        case 4:
        case 5:
          (__builtin_expect(!("" && 0), ) ? (void)0
                                                                  : (void)0);
        }
      }
    }
}
void *f_91(void *arg) {
  while (1)
    ;
}
int;

int d_97;

int f_99(res);

int f_101(res);

uint32_t f_103() {
  while (1)
    ;
}

```

**Comment by dsainati1** [comment]
To clarify: `cn verify` run on this file should abort execution because it runs out of file descriptors? Locally if I build CN to version `git-77cdad7dc [2024-08-28 08:53:13 -0700]`, `cn verify` finishes execution and reports verification errors. Should I be using a different command?

**Comment by peterohanley** [comment]
Yes. What is your maximum number of file descriptors? `ulimit -n`? For me it's 256 (the default)

**Comment by dsainati1** [comment]
Aha, mine is `1048575` for some reason, that would explain a lot!

**Comment by dsainati1** [comment]
Okay i can repro the issue now on `master` and confirmed that https://github.com/rems-project/cerberus/pull/547 does indeed fix it. Will add a test.

**Comment by kmemarian** [comment]
I tried PR #547 and it does fix the issue for me too. In case you need it for CI, the tutorial tests previously failing with `EMFILE` (with limit at 256) are:
```
cn-tutorial/src/examples/append.c
cn-tutorial/src/examples/append2.c
cn-tutorial/src/examples/list_copy.c
cn-tutorial/src/examples/list_free.c
cn-tutorial/src/examples/list_length.c
cn-tutorial/src/examples/list_rev.c
cn-tutorial/src/examples/list_rev_alt.c
cn-tutorial/src/examples/mergesort.c
cn-tutorial/src/examples/queue_pop.c
cn-tutorial/src/examples/queue_pop_unified.c
cn-tutorial/src/examples/queue_push.c
cn-tutorial/src/examples/queue_push_induction.c
cn-tutorial/src/examples/slf_incr2.c
cn-tutorial/src/examples/slf_incr2_alias.c
cn-tutorial/src/examples/slf_length_acc.c
cn-tutorial/src/examples/slf_sized_stack.c
```
