### ISSUE TITLE
[CN] Bad parsing error message

### ISSUE THREAD

**Issue by dc-mak** [rems-project/cerberus#382]
Strangely enough, it disappears if you remove the first empty-magic comment.

```
11:23 ➜  cerberus git:(cn-exec-leak-checking) ✗ cat bad_parser_error.c && cn bad_parser_error.c
/*@
@*/

/*@

datatype DT { Cons {} }

function [rec] (datatype DT) split(datatype DT xs) {
    match xs {
        Cons {} =>
            Cons {}
    }
}

@*/

:1:1: error: unexpected token before 'CPARSER_DRIVER(lex_buffer_len = 1; offset = 885; start_index = -885; end_index = 0)'
parsing "cn_toplevel'": expected "cn_toplevel"
```

**Comment by kmemarian** [comment]
I don't yet understand what's happening, but:

1. toplevel magic comments are parsed in reverse order
2. the issue is not specific to having an empty magic comment. Instead, if the parsing of a toplevel magic comment fails, then the parsing of the next one (regardless of its content) fails with that funky error (somehow the lexbuf contains the error message of the previous failure?)

I suspect there is some bad interaction between the use of the exception monad and the stateful-ness of the parsing/lexing. We probably should not use the monad inside the `C_parser_driver` module, and just wrap the final result with `Exception.except_return`.

**Comment by dc-mak** [comment]
Ok,  so the issue is that the lexer is stateful and the parse error occurs after a `UNAME(Cons)`. When the next thing is parsed (as you helpfully hinted, in reverse, would have been stumped on that for a while), the first thing the lexer does is issue a `VARIABLE` token - with the positions of the previous magic comment. By then the old buffer `MenhirLib.ErrorReports.wrap (..)` is gone and the token position is out of bounds for the new one.

I have some code that seems to fix this, but I'm not sure about it.
```diff
13:35 ➜  cerberus git:(master) ✗ git --no-pager diff
diff --git a/parsers/c/c_lexer.mll b/parsers/c/c_lexer.mll
index f7f3a42c2..84590d21c 100644
--- a/parsers/c/c_lexer.mll
+++ b/parsers/c/c_lexer.mll
@@ -588,7 +588,9 @@ type lexer_state =

 let lexer_state = ref LSRegular

-let lexer : inside_cn:bool -> lexbuf -> token = fun ~inside_cn lexbuf ->
+let lexer : inside_cn:bool -> lexbuf -> token = fun ~inside_cn ->
+  if inside_cn then lexer_state := LSRegular;
+  fun lexbuf ->
   match !lexer_state with
   | LSRegular ->
       let at_magic_comments = Switches.(has_switch SW_at_magic_comments) in
```

**Comment by dc-mak** [comment]
https://github.com/rems-project/cerberus/commit/6e1f8c80088a09554b7557d6aaea6db4dcd95006

Fix as above, test added in this commit. Closing issue.
