### ISSUE TITLE
[CN] Inconsistent assumptions when declaring a struct with scalar elements unchanged

### ISSUE THREAD

**Issue by peterohanley** [rems-project/cerberus#399]
The reproduction:

```
#include <stdint.h>

struct s {
  uint8_t sca;
};

static int f(struct s *v)
/*@
    requires take si = Owned<struct s>(v);
    ensures take so = Owned<struct s>(v);
@*/
{
  for (int i = 0; i < 1; ++i)
  /*@ inv 0i32 <= i;
      i <= 1i32;
      take sinv = Owned<struct s>(v);
    //{v} unchanged;
  @*/
  {
  }

  return 0;
}
```

```
% cn verify assumptions.c
[1/1]: f
assumptions.c:22:3: error: Missing resource for returning
  return 0;
  ^~~~~~~~~ 
Resource needed: Owned<struct s>(v)
      assumptions.c:10:18: (arg so)
  which requires: Owned<unsigned ichar>(member_shift<s>(v, sca))
      other location (Dune__exe__ResourceInference.General.predicate_request)  (arg sca)
State file: ...
```
```
...
Available resources

Owned<unsigned ichar>(member_shift<s>(O_v0, sca))(sinv.sca)
...
```

This indicates CN needs to know `v` hasn't changed but if you uncomment that unchanged line you get an inconsistent assumptions error. If `sca` is changed to `sca[1]` it verifies fine.

This is different from #398, which is about the error itself. This is perhaps a bug in the implementation of #385?

**Comment by dc-mak** [comment]
~It's not a bug in the implementation of #385, it's the fact that `{v} unchanged` means `take sinv = Owned(v); sinv == si` and so ownership of the same pointer is being claimed twice.~
Update: see #443 about semantics of unchanged.

The bug is actually in the fact that CN unfolds the struct into ownership of its members but it doesn't/can't fold it back up for some reason.

**Comment by cp526** [comment]
@dc-mak No, `{v} unchanged` in itself doesn't add a `take ... = Owned(...)`.

**Comment by peterohanley** [comment]
I found the inconsistent assumption: `cn` is asserting that the new value of `v` is separated from the old value, and also that they are the same value.

```
(u64)&v + 8'u64 <= (u64)O_v0 || (u64)O_v0 + 1'u64 <= (u64)&v
(u64)&i + 4'u64 <= (u64)&v || (u64)&v + 8'u64 <= (u64)&i
(u64)&i + 4'u64 <= (u64)O_v0 || (u64)O_v0 + 1'u64 <= (u64)&i
(u64)&v->sca + 1'u64 <= (u64)&v || (u64)&v + 8'u64 <= (u64)&v->sca
(u64)&v->sca + 1'u64 <= (u64)&i || (u64)&i + 4'u64 <= (u64)&v->sca
(u64)&v->sca + 1'u64 <= (u64)O_v0 || (u64)O_v0 + 1'u64 <= (u64)&v->sca <----- separated
(u64)&v < (u64)&v + 8'u64
(u64)&i < (u64)&i + 4'u64
(u64)v < (u64)v + 1'u64
(u64)O_v0 < (u64)O_v0 + 1'u64
0'i32 <= O_i0
O_i0 <= 1'i32
O_v0 == v <---- the same
```

**Comment by peterohanley** [comment]
Any use of `accesses` seems to trigger this.

```
int y;
void f()
  /*$ accesses y; $*/
{
  for (int x = 0; x < 1; x++) {
  }
}
```
This seems to be the culprit:
```
(u64)&y + 4'u64 <= (u64)&x || (u64)&x + 4'u64 <= (u64)&y
(u64)&x + 4'u64 <= (u64)&y || (u64)&y + 4'u64 <= (u64)&x
(u64)&y < (u64)&y + 4'u64 <---- normal
(u64)&x < (u64)&x + 4'u64
(u64)&y + 4'u64 <= (u64)&y <---- weird
```

**Comment by peterohanley** [comment]
This is holding up TA2 work.

**Comment by dc-mak** [comment]
> Any use of `accesses` seems to trigger this.
> 
> ```
> int y;
> void f()
>   /*$ accesses y; $*/
> {
>   for (int x = 0; x < 1; x++) {
>   }
> }
> ```
> 
> This seems to be the culprit:
> 
> ```
> (u64)&y + 4'u64 <= (u64)&x || (u64)&x + 4'u64 <= (u64)&y
> (u64)&x + 4'u64 <= (u64)&y || (u64)&y + 4'u64 <= (u64)&x
> (u64)&y < (u64)&y + 4'u64 <---- normal
> (u64)&x < (u64)&x + 4'u64
> (u64)&y + 4'u64 <= (u64)&y <---- weird
> ```

~~That does look very strange, but I'm unable to reproduce:~~ Nvm, I eventually noticed the `$` rather than the `@`. Thank you for the cut down example, please paste in the command next time.

**Comment by dc-mak** [comment]
The constraints are downstream of the ownership, which seems to be being duplicated: 
```
Owned<signed int>(&y)(O_y2), <--- owning &y
Owned<signed int>(&x)(O_x0), 
Alloc(&x)(A_x0),
Owned<signed int>(&y)(O_y0) <--- and again, owning &y
```

Similarly, I strongly suspect the first example is also downstream of ownership being claimed twice, but in a bit more subtle way:
```
Owned<struct s>(O_v0)(sinv)
Owned<struct s*>(&v)(O_v0), <-- this is owning the whole struct (.sca + padding)
Alloc(&v)(A_v0),
Owned<signed int>(&i)(O_i0), 
Alloc(&i)(A_i0),
Owned<unsigned ichar>(&v->sca)(si.sca) <-- and then this is owning .sca again
```

**Comment by peterohanley** [comment]
I was concerned about the ownership in the invariant but it used to work and it's still required (unused resource error if all resources aren't mentioned in the loop invariant). The `accesses` example doesn't have any explicit invariant at all happily but I presume always includes something like an `unchanged` annotation automatically.

> Similarly, I strongly suspect the first example is also downstream of ownership being claimed twice, but in a bit more subtle way:

Did you mean like this? Otherwise I'm missing something.
```
Owned<struct s>(O_v0)(sinv) <-- this is owning the whole struct (.sca + padding)
Owned<struct s*>(&v)(O_v0), <-- this owns the argument
Alloc(&v)(A_v0),
Owned<signed int>(&i)(O_i0), 
Alloc(&i)(A_i0),
Owned<unsigned ichar>(&v->sca)(si.sca) <-- and then this is owning .sca again
```

**Comment by dc-mak** [comment]
Yes that's right, I got confused/forget that `O_v0 == v` .

**Comment by dc-mak** [comment]
I can't speak for how it used to work, but here's what I have so far. 
* #274 demonstrates that labels take ownership of a stack variable automatically. That now demonstrates a different behaviour (inconsistent assumptions), because of #385.
* * The effect of #385 is to turn any double-`Owned`s into inconsistent assumptions.
* This leads me to believe, that it looks like looks like a similar thing is happening with accessed globals too (but in this case, CN is doing the double-`Owned`, which is definitely a bug, which I think I've located).
* Without the `take` in the `struct s` example, you get the `inconsistent` error.
* Without the `take` in the `struct s` example, there's `leftover unused resource`.


| type of variable | with `inv take` | no loop spec |
|------------------|-----------------|----------------|
|  global/`acesses` | inconsistent (why?) | inconsistent (why?) | 
| stack | inconsistent (expected) | works (expected) |
| argument | inconsistent (why?) | leftover resource (why?) |

~~All of this suggests that when checking labels (loops), CN is leaking Owneds into the scope of loops, _as well as_ automatically adding globals/stack variables to the "return type" of loops.~~ I have no clue what's going on.

**Comment by dc-mak** [comment]
Fixing this is non-obvious:
1. Add everything into the loop spec (would require lots of `unchanged`s, e.g. including for all globals, not clear if it's possible).
2. Stop the leaking of all resources into labels (would require `take`-ing stack variables)
3. Figure out a way to filter the leaked-in resources to only include stack variables (globals, and parameters are treated specially).

**Comment by podhrmic** [comment]
@septract FYI this is one of the blocking issues

**Comment by cp526** [comment]
This should be fixed by https://github.com/rems-project/cerberus/pull/565 .

Please re-open if that's not the case.
