### ISSUE TITLE
[CN] Update zarith dep. >= 1.13

### ISSUE THREAD

**Issue by podhrmic** [rems-project/cerberus#658]
There are two failures going right now with the CI:

1. [this commit](https://github.com/rems-project/cerberus/commit/ccc8fb4dd461f30d62b8bf6db1e52ba7afa0e53a) broke the [docker action](https://github.com/rems-project/cerberus/actions/workflows/docker.yml) - because the action is scheduled, it is not easily visible and is easy to miss
2. commit e73d6a1bb263980a6c6aa699e38aa0c7bbd476c3 broke the CI build - specifically the CN test step, as a test file generated an uncaught exception in [this line](https://github.com/rems-project/cerberus/actions/runs/11468005495/job/31949217625#step:14:249)

Number 1 happened because the docker build is *different* than the CI build - in the CI build, various dependencies are pinned. I will address this in a PR. 

For number 2. I would recommend requiring *all checks to pass* before merging (here is [how](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule)), and make `master` a protected branch that can be merged into only from PRs

**Comment by dc-mak** [comment]
1. We scheduled because the docker build is very slow. We can change the frequency if you think that is appropriate.
2. The build break is spurious/unrelated to that commit, and we were aware of it when it happened. We've been busy with paper deadlines.

**Comment by dc-mak** [comment]
@kmemarian can comment about protecting the master branch for a green CI

**Comment by podhrmic** [comment]
Thanks for the context @dc-mak !
1. in that case - perhaps the best is to add a badge for each CI workflow, see an example [here](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge)
2. Understandable! To clarify - the issue is that the [CI workflow](https://github.com/rems-project/cerberus/blob/master/.github/workflows/ci.yml#L42) steps and the Makefile steps for building Cerberus/CN are not identical. The CI worfklow pins packages, and that seems to resolve the compilation issues. The CI worfklow should indeed just call the same commands you describe in the README - e.g. `make install_cn` etc

**Comment by dc-mak** [comment]
As I said elsewhere, "It would also be very helpful if you could show where you think the build commands are different", but I've had a look now

The bits in the CI which are relevant (i.e. ignoring everything related to the `with_coq` switch and pinning there)
```
        opam install --deps-only --yes ./cerberus-lib.opam
        opam pin --yes --no-action add cn .
        opam install --yes cn ocamlformat.0.26.2
```

The bits in the README:
```
opam install --deps-only ./cerberus-lib.opam ./cn.opam
make install_cn
```

There's a slight difference in that the CI does a `--deps-only` for `cerberus.opam` whereas the README does it for `cn.opam` as well.

The opam file for CN looks like this:
```
depends: [
  "cerberus-lib"
  "monomorphic"
  "ocaml" {>= "4.14.0"}
  "ppx_deriving"
  "cmdliner"
  "ocamlgraph"
]
build: [
  ["dune" "subst"] {pinned}
  ["dune"
    "build"
    "-p"
    name
    "--profile=release"
    "-j"
    jobs
    "@install"
    "@runtest" {with-test}
    "@doc" {with-doc}
  ]
]
```

The Makefile looks like this:
```
.PHONY: install_cn
install_cn: install cn
        @echo "[DUNE] install cn"
        $(Q)dune install cn
```

The Makefile and opam _both call dune_, the difference between is just the `-p cn` is a dune/opam-ism, then `--profile=release` is just to compile optimised and without debug info I think. They're both calling _the same dune install_ command.

I don't know why pinning vs not would make any difference, but that might be related to the fact that the opam version used in 1.2.

Also, given the error message, it looks more like the `zarith` version is too old, because that function is used in 1.13 (from one year ago, the latest is 1.14 from 3 months ago), so maybe we need to add `zarith >= 1.13` to the CN dependencies.

**Comment by podhrmic** [comment]
I see, thanks for the explanation!
Would you be opposed to changing the CI such that it calls the makefile directly, exactly the same as in the README (and the dockerfile)? Adding `zarith >= 1.13` could be a quick fix as well.

**Comment by dc-mak** [comment]
Yes, I would be opposed, because the opam build is autogenerated from dune for sandboxed release builds from scratch (and don’t pick up uncommitted files) and the Makefile is for fast local developer builds which are not sandboxed and can pick up uncommitted files.

The README is serving a dual purpose for users (opam) and developers (Makefile) so we need to think about how to update that.

Happy to add the zarith constraint and see what happens.
